#!/usr/bin/env bash
# -*- mode:sh -*-

# @author  Mohamed Amin Boubaker https://github.com/ccdd13
# @author  https://github.com/joelebeau
# @author  https://github.com/talwrii
# @license MIT

die() {
  echo >&2 "$*"
  exit 1
}

cleanup() {
  rm -f "$tmpfile"
}
trap cleanup EXIT INT QUIT TERM

# Run older ld (pseudo condition)

if [ "$#" == "0" ]; then
  profile=default
elif [ "$#" == "1" ]; then
  profile=$1
else
  die "usage $0 [profile]"
fi

extract_cookies() {

  if [ "$#" -ge 1 ]; then
    sqlfile="$1"
  else
    if tty -s; then
      sqlfile="-" # Will use 'cat' below to read stdin
    fi
  fi

  if [ "$sqlfile" != "-" ] && [ ! -r "$sqlfile" ]; then
    echo "Error. File $sqlfile is not readable." >&2
    exit 1
  fi

  # We have to copy cookies.sqlite, because FireFox has a lock on it
  cat "$sqlfile" >>"$tmpfile"

  # This is the format of the sqlite database:
  # CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, name TEXT, value TEXT, host TEXT, path TEXT,expiry INTEGER, lastAccessed INTEGER, isSecure INTEGER, isHttpOnly INTEGER);

  echo "# Netscape HTTP Cookie File"
  sqlite_query=(
    "select host,"
    "case substr(host,1,1)='.' when 0 then 'FALSE' else 'TRUE' end,"
    "path,"
    "case isSecure when 0 then 'FALSE' else 'TRUE' end,"
    "expiry,"
    "name,"
    "value"
    "from moz_cookies;"
  )
  sqlite3 -noheader -separator $'\t' "$tmpfile" <<<"${sqlite_query[@]}"

  cleanup

}

mkdir -p "$HOME"/.cache
tmpfile="$(mktemp "$HOME"/.cache/cookies.sqlite.XXXXXXXXXX)"
[ -z "$curlcookies" ] && curlcookies="$(mktemp "$HOME"/.cache/curlcookies.XXXXXXXXXX)"
[ -d "$HOME/Library/Application Support/Firefox/Profiles" ] &&
  cookies_sqlite_path="$HOME/Library/Application Support/Firefox/Profiles/*.$profile/cookies.sqlite" ||
  cookies_sqlite_path="$HOME/.mozilla/firefox/*.$profile/cookies.sqlite"
(
  IFS=
  # shellcheck disable=SC2086
  echo $cookies_sqlite_path
) | {
  read -r cookie_file
  extract_cookies "$cookie_file"
}
