#!/usr/bin/env bash

# @author  Mohamed Amin Boubaker https://github.com/ccdd13
# @author  https://github.com/talwrii
# @license MIT

set -o errexit
set -o nounset
set -o pipefail

cleanup() {
  rm -f "$curlcookies"
}
trap cleanup EXIT INT QUIT TERM

profile=default-release
skip=
args=()
for var in "$@"; do
  # Ignore known bad arguments
  case "$var" in
    -P)
      skip=yes
      ;;
    *)
      if [ -z "$skip" ]; then
        args+=("$var")
      else
        profile=$var
      fi
      skip=
      ;;
  esac
done

mkdir -p "$HOME"/.cache
curlcookies="$(mktemp "$HOME"/.cache/curlcookies.XXXXXXXXXX)"
cookiefire "$profile" >"$curlcookies"
curl -b "$curlcookies" "${args[@]:--h}"
