#!/usr/bin/env bash

# @author  Mohamed Amin Boubaker https://github.com/ccdd13
# @license MIT

mkdir       -p        "${HOME}/.local/bin" "${HOME}/.cache"
git   clone --depth 1 https://github.com/ccdd13/curlfire          "${HOME}/.cache/curlfire"
mv          -fv       "${HOME}/.cache/curlfire/cookiefire"        "${HOME}/.local/bin/cookiefire"
mv          -fv       "${HOME}/.cache/curlfire/curlfire"          "${HOME}/.local/bin/curlfire"
mv          -fv       "${HOME}/.cache/curlfire/curlfire-install"  "${HOME}/.local/bin/curlfire-install"
chmod u+x             "${HOME}/.local/bin/"*
rm          -rf       "${HOME}/.cache/curlfire"
echo "${PATH}" | grep -Eq "(^|:)${HOME}/.local/bin(:|)" || echo "PATH=${HOME}/.local/bin:\${PATH}" >> "${HOME}/.bashrc"
