#!/usr/bin/env bash

# @author  Mohamed Amin Boubaker https://github.com/ccdd13/curlfire
# @license MIT

dir="$(realpath $(dirname ${0}))"
oldpwd="$(pwd)"
cd "${dir}"
git reset --hard
git fetch --prune --all && git pull && git status && git gc --aggressive --prune
cd "${oldpwd}"
