name: curlfire CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        # Workaround for https://github.com/actions/runner/issues/241
        shell: script -q -e -c "bash --noprofile --norc -eo pipefail {0}"
        run: make test
